version: 1.0.{build}
clone_depth: 1
clone_folder: C:\work\src\github.com\therecipe\qt
environment:
  QT_DIR: C:\Qt
  GOPATH: C:\work
  ANDROID_SDK_DIR: C:\android-sdk-windows
  ANDROID_NDK_DIR: C:\android-ndk-r12b
install:
- cmd: >-
    set PATH=%PATH%;C:\Qt\Tools\mingw530_32\bin


    curl -sL --retry 3 -o %TMP%\android-sdk_r24.4.1-windows.zip https://dl.google.com/android/android-sdk_r24.4.1-windows.zip

    7z x %TMP%\android-sdk_r24.4.1-windows.zip -oC:\

    DEL %TMP%\android-sdk_r24.4.1-windows.zip /Q


    echo y | C:\android-sdk-windows\tools\android.bat -s update sdk -f -u -a -t 1,2,4,31


    curl -sL --retry 3 -o %TMP%\android-ndk-r12b-windows-x86_64.zip https://dl.google.com/android/repository/android-ndk-r12b-windows-x86_64.zip

    7z x %TMP%\android-ndk-r12b-windows-x86_64.zip -oC:\

    DEL %TMP%\android-ndk-r12b-windows-x86_64.zip /Q
build_script:
- cmd: >-
    %GOPATH%\src\github.com\therecipe\qt\setup.bat

    %GOPATH%\src\github.com\therecipe\qt\setup.bat android