language: go

dist: trusty
sudo: required

go: 1.7.1

matrix:
  include:
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.2

before_install:
  - export QT_QPA_PLATFORM=minimal

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 20 $GOPATH/src/github.com/therecipe/qt/internal/ci/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then killall "qtcreator"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ANDROID_SDK_DIR=/tmp/android-sdk-linux; fi

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then killall "Qt Creator"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ANDROID_SDK_DIR=/tmp/android-sdk-macosx; fi

  - export ANDROID_NDK_DIR=/tmp/android-ndk-r12b
  - sudo chown $USER /usr/local/bin/

script:
  - $GOPATH/src/github.com/therecipe/qt/setup.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios-simulator; fi
  - $GOPATH/src/github.com/therecipe/qt/setup.sh android
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish-emulator; fi
