language: go

dist: trusty
sudo: required

go: 1.7.1

env: DESKTOP=true ANDROID=true

matrix:
  include:
    - os: linux
      env: DESKTOP=true ANDROID=false QT_PKG_CONFIG=true PKG_CONFIG_PATH=/opt/qt57/lib/pkgconfig QT_DOC_DIR=/opt/qt57/doc QT_MISC_DIR=/opt/qt57

    - os: linux
      env: DESKTOP=true ANDROID=true QT_WINDOWS_CC=true

    - os: osx
      env: DESKTOP=true ANDROID=false

    - os: osx
      env: DESKTOP=false ANDROID=true

    - os: osx
      osx_image: xcode8
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

    - os: osx
      osx_image: xcode7.3
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

    - os: osx
      osx_image: xcode7.2
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

    - os: osx
      osx_image: xcode8
      env: DESKTOP=false ANDROID=false IOS=true

    - os: osx
      osx_image: xcode7.3
      env: DESKTOP=false ANDROID=false IOS=true

    - os: osx
      osx_image: xcode7.2
      env: DESKTOP=false ANDROID=false IOS=true

    - os: osx
      osx_image: xcode8
      env: DESKTOP=false ANDROID=false IOS_SIMULATOR=true

    - os: osx
      osx_image: xcode7.3
      env: DESKTOP=false ANDROID=false IOS_SIMULATOR=true

    - os: osx
      osx_image: xcode7.2
      env: DESKTOP=false ANDROID=false IOS_SIMULATOR=true

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 30 $GOPATH/src/github.com/therecipe/qt/internal/ci/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

script:
  - if [[ "$DESKTOP" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh; fi
  - if [[ "$ANDROID" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh android; fi
  - if [[ "$IOS" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios; fi
  - if [[ "$IOS_SIMULATOR" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios-simulator; fi
  - if [[ "$QT_WINDOWS_CC" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh windows; fi
