language: go

go:
  - 1.6.3
  - 1.7.1
  - tip

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode8
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode7.2

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then $GOPATH/src/github.com/therecipe/qt/internal/ci/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

before_script:
  - sudo chown $USER /usr/local/bin/
  - export QT_QPA_PLATFORM=minimal

script:
  - $GOPATH/src/github.com/therecipe/qt/setup.sh
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios-simulator; fi
  #- $GOPATH/src/github.com/therecipe/qt/setup.sh android
  #- $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish
  #- $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish-emulator
