language: go

dist: trusty
sudo: required

go: 1.7.1

env: DESKTOP=true ANDROID=true IOS=false SAILFISH=false

matrix:
  include:
    - os: osx
      osx_image:
        - xcode8
        - xcode7.3
        - xcode7.2
      env: DESKTOP=true ANDROID=false IOS=false SAILFISH=false

    - os: osx
      env: DESKTOP=false ANDROID=true IOS=false SAILFISH=false

    - os: osx
      osx_image:
        - xcode8
        - xcode7.3
        - xcode7.2
      env: DESKTOP=false ANDROID=false IOS=true SAILFISH=false

    - os: osx
      env: DESKTOP=false ANDROID=false IOS=false SAILFISH=true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export QT_QPA_PLATFORM=minimal; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 20 $GOPATH/src/github.com/therecipe/qt/internal/ci/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export ANDROID_SDK_DIR=/tmp/android-sdk-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export ANDROID_SDK_DIR=/tmp/android-sdk-macosx; fi
  - export ANDROID_NDK_DIR=/tmp/android-ndk-r12b

  - sudo chown $USER /usr/local/bin/

script:
  - if [[ "$DESKTOP" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh; fi
  - if [[ "$ANDROID" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh android; fi
  - if [[ "$IOS" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios; fi
  - if [[ "$IOS" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh ios-simulator; fi
  - if [[ "$SAILFISH" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish; fi
  - if [[ "$SAILFISH" == "true" ]]; then $GOPATH/src/github.com/therecipe/qt/setup.sh sailfish-emulator; fi
